<Project>
  <PropertyGroup>
    <BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Quests.Settings.Tests\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Quests.Settings.Tests\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
